import { createHash } from "node:crypto";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sources = {
  "project_context.json": "examples/petclinic/project_context.json",
  "gaps.json": "examples/petclinic/gaps.json",
  "implementation_package.json": "examples/petclinic/implementation_package.json",
  "architecture.md": "docs/architecture.md",
};

const artifacts = {};
for (const [name, relativePath] of Object.entries(sources)) {
  const text = await readFile(resolve(repoRoot, relativePath), "utf8");
  artifacts[name] = name.endsWith(".json") ? JSON.parse(text) : text;
}

const serialized = JSON.stringify(artifacts, null, 2);
// Reference/context revision: changes whenever any retrievable artifact changes,
// so the runtime response cache invalidates itself without a manual bump.
const revision = createHash("sha256").update(serialized).digest("hex").slice(0, 16);

const outputPath = resolve(repoRoot, "functions/_lib/artifacts.generated.js");
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by scripts/generate_public_artifacts.mjs. Do not edit directly.\nexport const ARTIFACTS_REVISION = ${JSON.stringify(revision)};\nexport const ARTIFACTS = ${serialized};\n`,
  "utf8",
);
