import { createHash } from "node:crypto";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Public requirement registry. Adding a requirement here is the only step needed to
// expose it to the runtime: the retrieval layer and the API both read this registry.
const REQUIREMENTS = [
  {
    id: "owner-city-search",
    label: "飼い主検索に市区町村の条件を追加する",
    summary: "既存の姓検索に、市区町村の条件を追加する要件です。",
    basePath: "examples/petclinic",
  },
  {
    id: "same-day-visit",
    label: "当日の診療予約を登録できるようにする",
    summary: "翌日以降しか受け付けない診療予約を、当日にも広げる要件です。",
    basePath: "examples/petclinic-same-day-visit",
  },
  {
    id: "outline-restore-nested-documents",
    label: "ゴミ箱から復元した文書の子文書も一緒に復元する",
    summary: "削除は子文書へ波及するのに、復元は対象の文書だけを戻す非対称を変える要件です。",
    basePath: "examples/outline-restore-nested-documents",
  },
];

// Retrievable per requirement. The route table in retrieval.js maps onto these names.
const REQUIREMENT_ARTIFACTS = ["project_context.json", "gaps.json", "implementation_package.json"];

// Retrievable for every requirement: Forge's own design is not requirement-specific.
const SHARED_SOURCES = {
  "architecture.md": "docs/architecture.md",
};

async function loadArtifact(relativePath, name) {
  const text = await readFile(resolve(repoRoot, relativePath), "utf8");
  return name.endsWith(".json") ? JSON.parse(text) : text;
}

const requirements = {};
for (const requirement of REQUIREMENTS) {
  const artifacts = {};
  for (const name of REQUIREMENT_ARTIFACTS) {
    const relativePath = `${requirement.basePath}/${name}`;
    const artifact = await loadArtifact(relativePath, name);
    // A mismatch here would let the runtime serve one requirement's evidence under
    // another requirement's id, so it fails the build instead of shipping.
    if (artifact.requirement_id !== requirement.id) {
      throw new Error(
        `${relativePath}: requirement_id is ${JSON.stringify(artifact.requirement_id)}, expected ${JSON.stringify(requirement.id)}`,
      );
    }
    artifacts[name] = artifact;
  }
  requirements[requirement.id] = {
    id: requirement.id,
    label: requirement.label,
    summary: requirement.summary,
    base_path: requirement.basePath,
    artifacts,
  };
}

const shared = {};
for (const [name, relativePath] of Object.entries(SHARED_SOURCES)) {
  shared[name] = await loadArtifact(relativePath, name);
}

const payload = { requirements, shared };
const serialized = JSON.stringify(payload, null, 2);
// Reference/context revision: changes whenever any retrievable artifact of any
// requirement changes, so the runtime response cache invalidates itself without a
// manual bump.
const revision = createHash("sha256").update(serialized).digest("hex").slice(0, 16);

const outputPath = resolve(repoRoot, "functions/_lib/artifacts.generated.js");
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  [
    "// Generated by scripts/generate_public_artifacts.mjs. Do not edit directly.",
    `export const ARTIFACTS_REVISION = ${JSON.stringify(revision)};`,
    `export const DEFAULT_REQUIREMENT_ID = ${JSON.stringify(REQUIREMENTS[0].id)};`,
    `export const REQUIREMENT_ARTIFACT_NAMES = ${JSON.stringify(REQUIREMENT_ARTIFACTS)};`,
    `export const REQUIREMENTS = ${JSON.stringify(requirements, null, 2)};`,
    `export const SHARED_ARTIFACTS = ${JSON.stringify(shared, null, 2)};`,
    "",
  ].join("\n"),
  "utf8",
);
